name: Release Notes Generator
run-name: Release Notes Generator

on: 
  workflow_dispatch:
    inputs:
      new-release-tag:
        description: 'Tag name of the *new* release'
        required: true
        type: string
        default: 'e.g., v1.1 or v2.0'
      previous-release-reference:
        description: 'Tag name of the *previous* release or the commit SHA right *before* the first commit in the new release'
        required: true
        type: string
        default: 'e.g., v1.0 or 2f4a6b2'
      release-notes-source:
        description: 'Release Notes Source'
        required: true
        type: choice
        options:
          - Commit Messages
          - Pull Requests
        default: 'Pull Requests'
      pr-release-notes-mode:
        description: 'Release Notes Mode (only affects release notes if you chose source as Pull Requests)'
        required: false
        type: choice
        options:
          - Short
          - Full
        default: 'Full'

jobs:
  run-script-to-generate-release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    env:
      NEW_RELEASE_TAG: ${{ inputs.new-release-tag }}
      PREVIOUS_RELEASE_REFERENCE: ${{ inputs.previous-release-reference }}
      RELEASE_NOTES_SOURCE: ${{ inputs.release-notes-source }}
      RELEASE_NOTES_MODE: ${{ inputs.pr-release-notes-mode }}
      # secrets.GITHUB_TOKEN is automatically generated by GitHub for each workflow run
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Copy this repository to the Linux runner
        uses: actions/checkout@v4
        with:
          # By default actions/checkout fetches the .git folder with only a small part of the git history
          # usually the latest commit only, and my release notes script needs all the git history
          # so I need to add this "fetch-depth: 0", which makes it fetch ALL the git history/commit messages
          fetch-depth: 0

      - name: Install libcurl
        run: sudo apt install libcurl4-openssl-dev

      - name: Download nlohmann json.hpp header file
        run: wget https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp

      - name: Build the script
        run: g++ -o release_notes_generator release_notes_generator.cpp -lcurl -I.
      
      # I am doing this extra step to make the workflow work with draft releases
      # since a draft release's tag hasn't yet been created in the git history
      # I can't use it's tag in the release notes script as a reference to the last commit in the release
      - name: Get the commit SHA that the new release tag will be added on
        id: get-new-release-commit-sha
        run: |
          NEW_RELEASE_COMMIT_SHA=$(gh release view "$NEW_RELEASE_TAG" --json targetCommitish --jq .targetCommitish)
          echo "NEW_RELEASE_COMMIT_SHA=$NEW_RELEASE_COMMIT_SHA" >> "$GITHUB_OUTPUT"

      - name: Run the release notes script with the needed parameters
        env:
          NEW_RELEASE_COMMIT_SHA: ${{ steps.get-new-release-commit-sha.outputs.NEW_RELEASE_COMMIT_SHA }}
        run: |
          ./release_notes_generator "$RELEASE_NOTES_SOURCE" "$PREVIOUS_RELEASE_REFERENCE" "$NEW_RELEASE_COMMIT_SHA" "$RELEASE_NOTES_MODE" "$GH_TOKEN"
      
      - name: Update the new GitHub release description with the generated release notes
        # GitHub's cli tool "gh" automatically uses the GH_TOKEN environment variable
        run: |
          gh release edit "$NEW_RELEASE_TAG" --notes-file release_notes.md
          gh release upload "$NEW_RELEASE_TAG" release_notes.html