name: Generate Release Notes
run-name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  run-script-to-generate-release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Copy this repository to the Linux runner
        uses: actions/checkout@v4
        with:
          # By default actions/checkout fetches the .git folder with only a small part of the git history
          # usually the latest commit only, and my release notes script needs all the git history
          # so I need to add this "fetch-depth: 0", which makes it fetch ALL the git history/commit messages
          fetch-depth: 0

      - name: Install libcurl
        run: sudo apt install libcurl4-openssl-dev

      - name: Download nlohmann json.hpp header file
        run: |
          wget https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp

      - name: Run make to build the script
        run: make

      - name: Run the script using commit messages as source
        run: ./release_notes_generator message
      
      - name: Update GitHub release description with generated release notes
        # secrets.GITHUB_TOKEN is automatically generated by GitHub for each workflow run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # I read the tag name of the release that triggered this workflow, by accessing its JSON value using "jq"
        # Details related to the release are in the JSON file/event payload located in the GITHUB_EVENT_PATH environment variable
        # GitHub's cli tool "gh" automatically uses the GITHUB_TOKEN environment variable
        run: |
          RELEASE_TAG_NAME=$(jq -r .release.tag_name "$GITHUB_EVENT_PATH")
          gh release edit $RELEASE_TAG_NAME --notes-file release_notes.md
          gh release upload $RELEASE_TAG_NAME release_notes.html