name: Generate Release Notes
run-name: Generate Release Notes

on: 
  workflow_dispatch:
    inputs:
      new-release-reference:
        description: 'New Release Tag Name or Commit SHA of the Last Commit in the New Release'
        required: true
        type: string
        default: 'e.g., v2.0 or 3a77b2a'
      previous-release-reference:
        description: 'Previous Release Tag Name or Commit SHA of the Commit Before the First Commit in the New Release'
        required: true
        type: string
        default: 'e.g., v1.0 or 2f4a6b2'
      release-notes-source:
        description: 'Release Notes Source'
        required: true
        type: choice
        options:
          - Commit Messages
          - Pull Requests
        default: 'Pull Requests'
      pr-release-notes-mode:
        description: 'Release Notes Mode (only affects release notes if you chose source as Pull Requests)'
        required: false
        type: choice
        options:
          - Short
          - Full
        default: 'Full'

jobs:
  run-script-to-generate-release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    env:
      NEW_RELEASE_REFERENCE: ${{ inputs.new-release-reference }}
      PREVIOUS_RELEASE_REFERENCE: ${{ inputs.previous-release-reference }}
      RELEASE_NOTES_SOURCE: ${{ inputs.release-notes-source }}
      RELEASE_NOTES_MODE: ${{ inputs.pr-release-notes-mode }}
      # secrets.GITHUB_TOKEN is automatically generated by GitHub for each workflow run
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Copy this repository to the Linux runner
        uses: actions/checkout@v4
        with:
          # By default actions/checkout fetches the .git folder with only a small part of the git history
          # usually the latest commit only, and my release notes script needs all the git history
          # so I need to add this "fetch-depth: 0", which makes it fetch ALL the git history/commit messages
          fetch-depth: 0

      - name: Install libcurl
        run: sudo apt install libcurl4-openssl-dev

      - name: Download nlohmann json.hpp header file
        run: wget https://raw.githubusercontent.com/nlohmann/json/develop/single_include/nlohmann/json.hpp

      - name: Build the script
        run: g++ -o release_notes_generator release_notes_generator.cpp -lcurl -I.

      - name: Run the script giving it the workflow dispatch inputs obtained
        run: |
          ./release_notes_generator "$RELEASE_NOTES_SOURCE" "$PREVIOUS_RELEASE_REFERENCE" "$NEW_RELEASE_REFERENCE" 
          "$RELEASE_NOTES_MODE" "$GITHUB_TOKEN"
      
      - name: Update new GitHub release description with generated release notes
        # GitHub's cli tool "gh" automatically uses the GITHUB_TOKEN environment variable
        run: |
          gh release edit "$NEW_RELEASE_REFERENCE" --notes-file release_notes.md
          gh release upload "$NEW_RELEASE_REFERENCE" release_notes.html